name: Language version check

on: 
  push:
    paths:
      - ".github/workflows/version.yml"
  workflow_dispatch:
    
jobs:
  build:
    name: Python setup
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.10"
      - run: python --version
      