name: pr_labels

on:
  pull_request:
    types: [opened, reopened]
    
jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add 'bug' label to new pr's
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            
            const repo = context.repo.repo;
            
            const issue_number = context.issue.number;

            console.log(`owner is ${owner}, repo is ${repo}, issue number is ${issue_number}`);
            
            github.rest.issues.addLabels({
              owner, repo, issue_number,
              labels: ['bug']
            });