name: pr_labels

on:
  pull_request:
    types: [opened]
    
jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add 'bug' label to new pr's
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['bug']
            });