# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Language version check

on: 
  push:
    paths:
      - ".github/workflows/versions.yaml"
  workflow_dispatch:
    
jobs:
  build:
    name: Python setup
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps: 
      - run: python --version
      - uses: actions/setup-python@v5
        with: 
          python-version: "3.10"
      - run: python --version
      