name: version checking

on: 
  push:
    paths:
      - ".github/workflows/version.yml"
  workflow_dispatch:
    
jobs:
  build:
    name: Both go versions
    runs-on: ubuntu-latest
    steps: 
      - run: go version
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - run: go version